### ISSUE TITLE
Question: Is it possible to reference icons in sass file?

### ISSUE THREAD

**Issue by kimbaudi** [react-icons/react-icons#246]
Hi, I would like to be able to use the icons in a sass file with the ::before and ::after psuedo selectors. 

```html
<i class="fa-lg icon"></i>
```

```scss


.icon {
    &::before {
      font-family: "Font Awesome 5 Free";
      font-weight: 400;
      content: "\f185";
    }

    &::after {
      font-family: "Font Awesome 5 Free";
      font-weight: 900;
      content: "\f111";
      position: absolute;
      font-size: 0.625rem;
    }
}
```

Is this possible with react-icons? Or I can only use react-icons in JavaScript and need an alternate way to use font-awesome in sass?
