### ISSUE TITLE
Color property does not work on Grommet-icons

### ISSUE THREAD

**Issue by fany395** [react-icons/react-icons#334]
**Describe the bug**
When using icons from the Grommet-Icons library version 4.4.0, it is not possible to change component colors, nor by setting the color property inside the icon or by external styling files.

**Minimum sample repository**
https://github.com/grommet/grommet-icons

**Expected behavior**
When adding color property to an icon it was expected to change the color or the icon to inherit color from the parent div.

**Desktop (fill in the following information):**
  - Device: PC, telePhone
  - OS: linux
  - Browser: chrome, firefox
  - Version Chrome -> Version 83.0.4103.116 (Official version) 64 bits
Firefox-> Version 68.10.0esr (64-bit)

**Comment by jaydattc** [comment]
Yes, It didn't for me as well.
currently using this in a global css file works.
```css
path, g {
  stroke: currentColor;
  fill: currentColor; // which ever property you want to have same color as text
}
```
