### ISSUE TITLE
Allow for customizing the stroke/outline width of the icons.

### ISSUE THREAD

**Issue by nisarhassan12** [react-icons/react-icons#395]
Hi. Thanks to everyone who contributed to the `react-icons` library.

Would be nice if there is a way via which one can increase/decrease the `stroke-width` of an icon.

I want to reduce the `stroke-width` of the following icons:

![image](https://user-images.githubusercontent.com/46004116/103485523-c7035c80-4e18-11eb-8c4a-4c0c725e456b.png)

I tried adding a class to the icons:

```jsx
<RiLock2Line className="faq-icon" />
```

and then in CSS reduced the stoke width:

```css
.faq-icon {
  stroke-width: 8px;
}

```

but it does not work:

![image](https://user-images.githubusercontent.com/46004116/103485554-eac6a280-4e18-11eb-86a0-7dd040d35830.png)

**Comment by dinythomas89** [comment]
svg path {
  stroke-width: 1;
}
worked fine

**Comment by gustavodamazio** [comment]
I found a palliative solution.

```tsx
{type === 'success' && <HiOutlineCheckCircle size="3rem" className="stroke-custom" />}
```
```css
.stroke-custom {
  path {
    stroke-width: 1.2px !important;
  }
}
```
